// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD93-ZXjro8Gr6oNnueP8Zn9XfpJ82DqiA',
    appId: '1:656543779944:android:ab174e2185d4d4b5b17fdd',
    messagingSenderId: '656543779944',
    projectId: 'stamp-1c1f9',
    storageBucket: 'stamp-1c1f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj1ssnTrS5MvBT897gR_05LIw9HSWIA4Y',
    appId: '1:656543779944:ios:e68d1f6af8b5fc3eb17fdd',
    messagingSenderId: '656543779944',
    projectId: 'stamp-1c1f9',
    storageBucket: 'stamp-1c1f9.firebasestorage.app',
    iosClientId: '656543779944-hgf3meaj0ef4e7idnv5aig9d0ea6nqc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoWZk-KprPMCNTscaUPUlxE1Yjbp5P0jA',
    appId: '1:656543779944:web:e68ac6d00cb19d4bb17fdd',
    messagingSenderId: '656543779944',
    projectId: 'stamp-1c1f9',
    authDomain: 'stamp-1c1f9.firebaseapp.com',
    storageBucket: 'stamp-1c1f9.firebasestorage.app',
    measurementId: 'G-54FG5MGQKS',
  );

}